sudo: required
language: python
python:
    - "3.6"

services:
    - docker


before_install:
    - docker build -t theaayushbajaj/social-sentiments .

script:
    - docker run theaayushbajaj/social-sentiments coverage report


